import type { Metadata } from "next";
import { Didact_Gothic, Exo_2, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Shared/Header";
import Footer from "@/components/Shared/Footer";

// const geistSans = Didact_Gothic({
//   variable: "--font-didact-gothic",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-didact-gothic",
//   subsets: ["latin"],
// });

const didact_gothic = Didact_Gothic({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-one",
});

const exo_2 = Exo_2({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-two",
});

const montserrat_alternates = Montserrat_Alternates({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-three",
});

export const metadata: Metadata = {
  title: "Ink Studio Gestion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${didact_gothic.variable} ${exo_2.variable} ${montserrat_alternates.variable} antialiased relative`}
      >
        {/* <div className="absolute top-0 left-0 w-full h-screen">
          <Header />
        </div> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
